AllCops:
  StringLiteralsFrozenByDefault: true
  Exclude:
    # - "answers/**/*.rb"

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: diff_comma
  
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: diff_comma

Naming/VariableNumber:
  EnforcedStyle: snake_case

Layout/LineLength:
  Max: 150

Metrics:
  Exclude:
    - "test/**/*"
    - "benchmarks/**/*"
    - "questions/**/*"
