AllCops:
  StringLiteralsFrozenByDefault: true

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/StringLiterals:
  EnforcedStyle: double_quotes

Naming/VariableNumber:
  EnforcedStyle: snake_case

Layout/LineLength:
  Max: 150

Metrics/MethodLength:
  Exclude:
    - "test/**/*"
